<?php
/**
 * RocketWeb
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category  RocketWeb
 * @package   MageOS_ShoppingFeed
 * @copyright Copyright (c) 2016 RocketWeb (http://rocketweb.com)
 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author    Rocket Web Inc.
 */

/** @var $block \MageOS\ShoppingFeed\Block\Adminhtml\Feed\Edit\Tab\Promotions */
?>

<div class="entry-edit form-inline">
    <?php if (strlen((string) $block->getTabNotice())): ?>
        <div class="messages">
            <div class="message message-notice">
                <?= $escaper->escapeHtml($block->getTabNotice(), ['strong']) ?>
            </div>
        </div>
    <?php endif; ?>
    <?= /* @noEscape */ $block->getFormHtml() ?>
</div>
<?= /* @noEscape */ $block->getChildHtml('form_after') ?>
