<?php

/* @var $block \MageOS\ShoppingFeed\Block\Adminhtml\Feed\Edit\Tab\Filters\FindReplace */
$element = $block->getElement();
?>
<?php $htmlId      = $block->getElement()->getHtmlId() ?>
<?php $htmlClass   = $block->getElement()->getClass() ?>
<?php $htmlName    = $block->getElement()->getName() ?>
<?php $options     = $block->getElement()->getValues(); ?>
<?php $value       = $block->getElement()->getValue(); ?>
<?php $value_other = $block->getData('delimiter_other_value'); ?>

<div class="admin__field field field-config_<?= $escaper->escapeHtmlAttr($htmlName)?> _required required">
    <?php echo $block->getElement()->getLabelHtml(); ?>
    <div class="admin__field-control control">
        <select id="<?= $escaper->escapeHtmlAttr($htmlId)?>" name="config[<?= $escaper->escapeHtmlAttr($htmlName)?>]" style="float: left;" title="<?= $escaper->escapeHtmlAttr($htmlName)?>" class=" _required select admin__control-select">
            <?php if (is_array($options) && count($options)): ?>
            <?php foreach ($options as $k => $v): ?>
                <option <?php if($value == $k) echo 'selected';?> value="<?= $escaper->escapeHtmlAttr($k)?>"><?= $escaper->escapeHtml($v)?></option>
            <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <input id="<?= $escaper->escapeHtmlAttr($htmlId)?>_other" style="<?php if($value != 'other') echo 'display:none;';?>width:120px;margin-left:20px;clear:right;" name="config[<?= $escaper->escapeHtmlAttr($htmlName)?>_other]" value="<?= $escaper->escapeHtmlAttr($value_other)?>" type="text" class="input-text admin__control-text">
    </div>
</div>
<script>
    require([
        "prototype",
        "mage/adminhtml/form"
    ], function (mageTemplate) {
        var elm = document.getElementById('<?= $escaper->escapeJs($htmlId)?>');
        var other_elm = document.getElementById('<?= $escaper->escapeJs($htmlId)?>_other');
        elm.addEventListener("change", function() {
            var val = elm.options[elm.selectedIndex].value;

            if (val != 'other') {
                $(other_elm).hide();
            } else {
                $(other_elm).show();
            }
        });
    });
</script>
